FROM mcr.microsoft.com/playwright/python:v1.49.1-jammy

WORKDIR /app

ARG FORCE_REBUILD=2026-01-28

# Install Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Run the ingestion script
CMD ["python", "ingest.py"]
